class SECRET:
    GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID"
    GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET"
    SUPER_SECRET = 'FLASK_SUPER_SECRET'

    class DB:
        HOST = 'DATABASE_HOST'
        DB = 'DATABASE_NAME'
        USER = 'DATABASE_USER'
        PW = 'DATABASE_SECRET'
        PORT = 'DATABASE_PORT'
